name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers the workflow on version tags like v1.0.0

permissions:
  contents: write  # Grant the workflow permission to write to the contents

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js (required for softprops/action-gh-release)
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Zip Plugin
      run: zip -r clone-post-or-page.zip . -x '*.git*'  # Create a ZIP file of the plugin

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: clone-post-or-page.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
